name: office_flutter_translate_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12+4
  introduction_screen: ^1.0.9
  dynamic_theme: ^1.0.1
  settings_ui: ^0.4.0
  share:
  url_launcher:
#  flutter_email_sender: ^3.0.1

  translator: ^0.1.5
  toast: ^0.1.5
  flutter_sticky_header: ^0.5.0
#  speech_to_text:

#  firebase_ml_vision: ^0.9.9





  provider:
  flutter_mobile_vision:
  flutter_tts:
  firebase_ml_vision:

  image_picker: ^0.6.7+11
  clipboard: ^0.1.2+8
  speech_to_text:
  highlight_text:
  avatar_glow:
#  double_back_to_close_app:
  dio:
  country_list_pick:
  country_provider:
  flutter_svg: ^0.20.0-nullsafety.3
  http: ^0.12.1
  page_transition: ^1.1.5
  font_awesome_flutter: ^8.8.1
  auto_size_text: ^2.1.0
  flutter_rating_bar:
  android_intent: ^0.3.7+3


  admob_flutter: ^1.0.1
  flutter_native_admob:
#  flutter_launcher_icons: "^0.7.3"
#  firebase_admob:
  change_app_package_name:
  rename: ^1.2.0
  mediation_test: ^0.0.2
#  facebook_audience_network: ^0.9.0




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
#    - assets/images/text_translate_page_bg.png
    - assets/images/
    - assets/icons/
    - assets/icons/common/
    - assets/icons/main_screen/
    - assets/icons/ocr_icons/
    - assets/icons/text_translate_screen/
    - assets/icons/drawer_icons/
#    - assets/icons/talk.png
#    - assets/icons/app_icon.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
